import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    keywords: ["nextjs", "react", "javascript"],
    title: {
        default: "Create Next App",
        template: "%s | Create Next App",
    },
    description: "Generated by create next app",
    openGraph: {
        description: "Generated by create next app",
        images: [
            {
                width: 1200,
                height: 630,
                alt: "Og Image Alt",
            },
        ],
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
